### ISSUE TITLE
ImportError: cannot import name 'mundiCatalogue' from 'mundilib' (/home/jovyan/lib/mundilib.py)

### ISSUE THREAD

**Issue by stephanbuettig** [VincentSaleh/Mundi_NotebookUsage#1]
The command `from mundilib import mundiCatalogue` produces the following error message:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-edc17cabe103> in <module>
----> 1 from mundilib import mundiCatalogue

ImportError: cannot import name 'mundiCatalogue' from 'mundilib' (/home/jovyan/lib/mundilib.py)
```

**Comment by VincentSaleh** [comment]
Answer given on Mundi Helpdesk:
"Hello Stephan,

We have recently updated mundilib to stick with PEP8 conventions. According to these conventions, class names must follow upper camel case format, that is, begin with a capital letter. That is why "mundiCatalogue" has been renamed "MundiCatalogue": your import problem should be fixed by merely changing the first letter. 

Note that the latest mundilib version is backward-compatible for most of the code, "mundiCatalogue" is one of the few exceptions.

At the moment, we unfortunately do not have any reference documentation for mundilib. However, we have a comprehensive set of notebook examples that can be found in the public folder. These examples are up-to-date and should cover most of your use cases. I encourage you to take a look at them.

I hope this will answer your questions.

Regards,

François-Xavier"
